### ISSUE TITLE
Suggestion for the progress bar

### ISSUE THREAD

**Issue by AISLVE** [Astromations/Hazy#40]
<img width="1920" alt="image" src="https://github.com/Astromations/Hazy/assets/121119257/6793cd53-7749-4a30-a8ad-851774a175b6">
this floating type with blur looks better in my opinion

**Comment by AISLVE** [comment]
no, i mean just the blur will do too, since ur theme looks almost the same

**Comment by Astromations** [comment]
You could add this as a snippet to blur it:

```css
.main-nowPlayingBar-nowPlayingBar {
  backdrop-filter: blur(10px)
}
```
