### ISSUE TITLE
Play bar not translucent 

### ISSUE THREAD

**Issue by Molynesio** [Astromations/Hazy#48]
Is there any way to make it that way? On the screenies I can see you can, any help is welcome Thanks
![spicetify](https://github.com/Astromations/Hazy/assets/102383268/f1ad6faf-5e8c-4bea-8f49-07d2dedb5aeb)

**Comment by Astromations** [comment]
It looks like you're using another theme and or extension with Hazy. They're overwriting the css which removes the Now Playing Bar background. Which specific themes/extensions are you using?

In the mean time, try adding this as a css snippet:

```css
.Root__now-playing-bar {
  background-color: var(--backdrop) !important; }
  ```
