### ISSUE TITLE
playbar and volume marker lags behind actual playbar and volume bar

### ISSUE THREAD

**Issue by sebyyyyy** [Astromations/Hazy#55]
the white marker on the playbar and volume bar does not follow the actual bar. it kind of irks me that they're not the same speed, pls fix?

https://github.com/Astromations/Hazy/assets/158838272/83abd0ac-6a18-4b63-b767-81bbb0c73522

On another note, I'd really like to be able to change the color of currently playing songs/like button color/playbar color, etc. from the usual spotify green to a different color. Is there any way to do this?

**Comment by Astromations** [comment]
Just fixed that in the latest commit. 

Regarding changing your colors, I don't know about a catch all, but you could add a css snippet to change the two most used variables:

```css
:root {
    --spice-button-active: #1ed760 !important;
    --spice-button: #1db954 !important;
}
```
