### ISSUE TITLE
Loop song button SVG slightly cut off

### ISSUE THREAD

**Issue by NeoNyaa** [Astromations/Hazy#88]
This is what it looks like before a fix I performed, which is probably very bad
![image](https://github.com/Astromations/Hazy/assets/56982408/228cd57a-0a3e-4954-85a4-2da6b82f895e)

This is what it looks like after the potentially bad fix
![image](https://github.com/Astromations/Hazy/assets/56982408/69dd8cb6-c08d-4c89-b2ac-f99a2fd7a635)

```css
.Svg-img-icon-small {
    overflow: visible;
}
```
