### ISSUE TITLE
Changing the color of the progress bar via color.ini

### ISSUE THREAD

**Issue by Noffelect** [Astromations/Hazy#99]
I created a question about this reason and it was solved, but every time I climb into the code to change the color is very tedious, especially when you release fixes for the theme. If it's not difficult, could you change the progress bar via color.ini?
![Spotify_DCKIJspL9R](https://github.com/Astromations/Hazy/assets/158531587/86548208-d7c8-44be-9f0e-54f38e677450)

**Comment by sanoojes** [comment]
You can change these colors by using a snippet and color.ini as follows

```css
# snippet or modify css

.progress-bar {
  --bg-color: rgba(255,555,255,.2);
  --fg-color: var(--spice-accent);
}
```

Setup accent colors
```ini
; color.ini
button                                = 30bf63
button-active                     = 30bf63
accent                                = 30bf63
```
